name: Publish Docker Container

on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: docker login --username ${{ github.actor }} --password ${{ secrets.DOCKER_TOKEN }} ghcr.io

    - name: Build and Push Docker Image
      run: |
        docker build . -t ghcr.io/${{ github.actor }}/blazordockertest:latest
        docker push ghcr.io/${{ github.actor }}/blazordockertest:latest
